# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-2'

menu:
- {name: 'Power BI 主页',        link: 'https://app.powerbi.com/home'}
- {name: '大中华区 Com-Ex 应用',  link: 'https://app.powerbi.com/Redirect?action=OpenApp&appId=ce37b19a-4f71-47f2-ab32-1a725e3f3505&ctid=4d3f6608-ec8c-4b1f-9484-274a4b699efb'}
- {name: '公司门户',              link: 'https://molnlycke.omniacloud.net/start'}
- {name: 'About',                url: 'about'}
- {name: 'Contact',              url: 'contact'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link:    'https://twitter.com/molnlyckehc'}
- {icon: 'facebook', link:   'https://www.facebook.com/molnlyckehc'}
- {icon: 'instagram', link:  'https://instagram.com/molnlyckehc'}
- {icon: 'envelope', link:   'mailto:hathaway.zhang@molnlycke.com'}
- {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
